on: workflow_dispatch

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ secrets.SRC_REPO_URL }}
          source_branch: "master"
          destination_repo: ${{ secrets.DEST_REPO_URL }}
          destination_branch: "master"
